{% set version = "1.0.0" %}

package:
  name: xtensorstack
  version: {{ version }}

source:
  path: ../src

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - clang
    - m2w64-gcc
    - m2w64-gcc-fortran
    - m2w64-make
    - m2-make
    - ninja
    - cmake
  host:
    - {{ compiler('cxx') }}
    - clang
    - m2w64-gcc
    - m2w64-gcc-fortran
    - m2w64-make
    - m2-make
    - ninja
    - cmake

outputs:
  - name: xtensorstack

about:
  home: https://github.com/sydx/xtensor-stack
  license: custom
  summary: 'xtensorstack - a full stack for numerical analysis'
  description: |
    A full stack for numerical analysis on multidimensional arrays (vectors, matrices,
    and tensors).
  dev_url: https://github.com/sydx/xtensor-stack
  doc_url: https://github.com/sydx/xtensor-stack
  doc_source_url: https://github.com/sydx/xtensor-stack
